---
yum_repositories:
- baseUrl: https://packages.microsoft.com/yumrepos/vscode
  file: ansible-vscode
  name: code
  description: Visual Studio Code
  gpg: https://packages.microsoft.com/keys/microsoft.asc
- baseUrl: https://downloads.k8slens.dev/rpm/packages
  name: lens-repo
  file: ansible-lens
  description: Lens Repo
  gpg: https://downloads.k8slens.dev/keys/gpg
- baseUrl: https://download.docker.com/linux/fedora/$releasever/source/stable
  name: docker-ce-stable-source
  file: ansible-docker
  description: Docker CE Stable - Sources
  gpg: https://download.docker.com/linux/fedora/gpg
- baseUrl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
  name: docker-ce-stable
  file: ansible-docker
  description: Docker CE Stable - $basearch
  gpg: https://download.docker.com/linux/fedora/gpg


yum_packages:
- dnf-plugins-core
- steam
- samba-client
- samba-common
- cifs-utils
- code
- lutris
- lens
- docker-ce
- docker-ce-cli 
- containerd.io 
- docker-buildx-plugin 
- docker-compose-plugin

flatpaks:
- org.keepassxc.KeePassXC
- com.usebottles.bottles
- com.discordapp.Discord
